version: '3.2'

services:
  remittance-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app_network

  mysql:
    container_name: cluster_db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: zurum-mysql
      MYSQL_DATABASE: sample_db
      MYSQL_USER: sample_db
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql_data:/data/db

networks:
  app_network:

volumes:
  mysql_data:
    driver: local